# Generated by Django 3.0.8 on 2020-08-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowfit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='armLength',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='arm length in cm'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dateOfBirth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='height in cm'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='inseam',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='inseam in cm'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneAlt',
            field=models.CharField(max_length=20, null=True, verbose_name='alternative phone number'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='pedalSystem',
            field=models.TextField(choices=[('Shimano', 'Shimano'), ('Look', 'Look'), ('Time', 'Time'), ('Speedplay', 'Speedplay')], verbose_name='pedal system'),
        ),
    ]
