# Generated by Django 3.0.8 on 2020-08-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slowfit', '0003_auto_20200809_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frame',
            options={'ordering': ['brand', 'name']},
        ),
        migrations.AlterModelOptions(
            name='framesize',
            options={'ordering': ['frame', 'name']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='armLength',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Arm Length in cm'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='EMail Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstName',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height in cm'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='inseam',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Inseam in cm'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastName',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneAlt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Alternative Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneMain',
            field=models.CharField(max_length=20, unique=True, verbose_name='Main Phone Number'),
        ),
        migrations.AlterField(
            model_name='fitsheet',
            name='bikeUsed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='slowfit.FrameSize', verbose_name='Bike Used'),
        ),
        migrations.AlterField(
            model_name='fitsheet',
            name='crankLength',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(165, '165mm'), (167.5, '167.5mm'), (170, '170mm'), (172.5, '172.5mm'), (175, '175mm')], null=True, verbose_name='Selected Current Crank Length'),
        ),
        migrations.AlterField(
            model_name='fitsheet',
            name='hx',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Selected Handlebar Reach (mm)'),
        ),
        migrations.AlterField(
            model_name='fitsheet',
            name='hy',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Selected Handlebar Stack (mm)'),
        ),
        migrations.AlterField(
            model_name='fitsheet',
            name='saddle',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Selected Saddle'),
        ),
        migrations.AlterField(
            model_name='fitsheet',
            name='saddleBarDrop',
            field=models.SmallIntegerField(blank=True, help_text='positive: saddle higher than bar, negative: bar higher than saddle', null=True, verbose_name='Selected Saddle to Bar Drop'),
        ),
        migrations.AlterField(
            model_name='fitsheet',
            name='saddleHeight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Selected Saddle Height'),
        ),
        migrations.AlterField(
            model_name='fitsheet',
            name='saddleSetback',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Selected Saddle Setback/Offset'),
        ),
        migrations.AlterField(
            model_name='fitsheet',
            name='sx',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Selected Current Saddle X'),
        ),
        migrations.AlterField(
            model_name='fitsheet',
            name='sy',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Selected Current Saddle Y'),
        ),
        migrations.AlterField(
            model_name='roadfitsheet',
            name='barDrop',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Selected Handlebar Drop'),
        ),
        migrations.AlterField(
            model_name='roadfitsheet',
            name='barReach',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Selected Handlebar Reach'),
        ),
        migrations.AlterField(
            model_name='roadfitsheet',
            name='barWidth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Selected Handlebar Width'),
        ),
        migrations.AlterField(
            model_name='roadfitsheet',
            name='webX',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Selected Handlebar Web X (Reach)'),
        ),
        migrations.AlterField(
            model_name='roadfitsheet',
            name='webY',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Selected Handlebar Web Y (Stack)'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='hx',
            field=models.PositiveSmallIntegerField(verbose_name='Handlebar Reach (mm)'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='hy',
            field=models.PositiveSmallIntegerField(verbose_name='Handlebar Stack (mm)'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='sx',
            field=models.SmallIntegerField(verbose_name='Saddle X'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='sy',
            field=models.PositiveSmallIntegerField(verbose_name='Saddle Y'),
        ),
        migrations.AlterField(
            model_name='ttfitsheet',
            name='aeroBar',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Selected Aerobar'),
        ),
        migrations.AlterField(
            model_name='ttfitsheet',
            name='extensions',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Selected Extensions'),
        ),
        migrations.AlterField(
            model_name='ttfitsheet',
            name='padWidth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pad Width (mm)'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='crankLength',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(165, '165mm'), (167.5, '167.5mm'), (170, '170mm'), (172.5, '172.5mm'), (175, '175mm')], null=True, verbose_name='Current Crank Length'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='currentBike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='slowfit.FrameSize', verbose_name='Current Bike'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='customerConcerns',
            field=models.TextField(blank=True, null=True, verbose_name="Rider's Specific Concerns"),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(verbose_name='Date of Visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Cycling Experience'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='fitterConcerns',
            field=models.TextField(blank=True, null=True, verbose_name="Fitter's Concerns"),
        ),
        migrations.AlterField(
            model_name='visit',
            name='goals',
            field=models.TextField(blank=True, null=True, verbose_name='Athletic Goals'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='hx',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Current Handlebar Reach (mm)'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='hy',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Current Handlebar Stack (mm)'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='injuries',
            field=models.TextField(blank=True, null=True, verbose_name='Injuries and Limitations'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='pedalSystem',
            field=models.TextField(blank=True, choices=[('Shimano Road', 'Shimano Road'), ('Shimano SPD', 'Shimano SPD'), ('Look', 'Look'), ('Time', 'Time'), ('Speedplay', 'Speedplay')], null=True, verbose_name='Pedal System'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='purpose',
            field=models.CharField(max_length=100, verbose_name='Purpose of Visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='saddle',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Current Saddle'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='saddleBarDrop',
            field=models.SmallIntegerField(blank=True, help_text='positive: saddle higher than bar, negative: bar higher than saddle', null=True, verbose_name='Current Saddle to Bar drop'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='saddleHeight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Current Saddle Height'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='saddleSetback',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Current Saddle Setback/Offset'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='sx',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Current Saddle X'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='sy',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Current Saddle Y'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Weight in kg'),
        ),
    ]
